cp -f /Users/an/Documents/moooyo/CBB/Source/CBB.CheckHelper/bin/Debug/*.dll /Users/an/Documents/moooyo/Components
cp -f /Users/an/Documents/moooyo/CBB/Source/CBB.ConfigurationHelper/bin/Debug/*.dll /Users/an/Documents/moooyo/Components
cp -f /Users/an/Documents/moooyo/CBB/Source/CBB.DataLayer/bin/Debug/*.dll /Users/an/Documents/moooyo/Components
cp -f /Users/an/Documents/moooyo/CBB/Source/CBB.Exception/bin/Debug/*.dll /Users/an/Documents/moooyo/Components
cp -f /Users/an/Documents/moooyo/CBB/Source/CBB.ImageHelper/bin/Debug/*.dll /Users/an/Documents/moooyo/Components
cp -f /Users/an/Documents/moooyo/CBB/Source/CBB.LocationFunctionHelper/bin/Debug/*.dll /Users/an/Documents/moooyo/Components
cp -f /Users/an/Documents/moooyo/CBB/Source/CBB.Logger/bin/Debug/*.dll /Users/an/Documents/moooyo/Components
cp -f /Users/an/Documents/moooyo/CBB/Source/CBB.MongoDB/bin/Debug/*.dll /Users/an/Documents/moooyo/Components
cp -f /Users/an/Documents/moooyo/CBB/Source/CBB.NetworkingHelper/bin/Debug/*.dll /Users/an/Documents/moooyo/Components
cp -f /Users/an/Documents/moooyo/CBB/Source/CBB.OAuth/bin/Debug/*.dll /Users/an/Documents/moooyo/Components
cp -f /Users/an/Documents/moooyo/CBB/Source/CBB.RankingHelper/bin/Debug/*.dll /Users/an/Documents/moooyo/Components
cp -f /Users/an/Documents/moooyo/CBB/Source/CBB.RecommendationHelper/bin/Debug/*.dll /Users/an/Documents/moooyo/Components
cp -f /Users/an/Documents/moooyo/CBB/Source/CBB.Security/bin/Debug/*.dll /Users/an/Documents/moooyo/Components