document.writeln("<div id=\"share\"><a href=\"javascript:window.open(\'http://share.renren.com/share/buttonshare.do?title=\'+encodeURIComponent(\'米柚网，欢乐的单身交友平台，欢迎大家的加入。\')+\'&link=\'+encodeURIComponent(\'http://www.moooyo.com\')+\'&content=\',\'_blank\',\'scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes\'); void 0\" style=\"color:#000000;text-decoration:none;font-size:12px;font-weight:normal\"><SPAN style=\"PADDING-RIGHT: 5px; PADDING-LEFT: 5px; FONT-SIZE: 12px; PADDING-BOTTOM: 0px; MARGIN-LEFT: 10px; CURSOR: pointer; PADDING-TOP: 5px\"><IMG alt=分享到人人网 src=\"http:\/\/s.xnimg.cn\/favicon-rr.ico\" align=absMiddle border=0 width=\"16\" height=\"16\" />&nbsp;分享到人人网<\/SPAN><\/a>");

document.writeln("<a href=\"javascript:window.open(\'http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=\'+encodeURIComponent(\'http://www.moooyo.com\')+\'&rcontent=\',\'_blank\',\'scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes\'); void 0\" style=\"color:#000000;text-decoration:none;font-size:12px;font-weight:normal\"><SPAN style=\"PADDING-RIGHT: 5px; PADDING-LEFT: 5px; FONT-SIZE: 12px; PADDING-BOTTOM: 0px; MARGIN-LEFT: 10px; CURSOR: pointer; PADDING-TOP: 5px\"><IMG alt=分享到QQ空间 src=\"http:\/\/qzone.qq.com\/favicon.ico\" align=absMiddle border=0 width=\"16\" height=\"16\" />&nbsp;分享到QQ空间<\/SPAN><\/a>");

document.writeln("<a href=\"javascript:window.open(\'http://cang.baidu.com/do/add?it='+encodeURIComponent(document.title.substring(0,76))+'&iu=\'+encodeURIComponent(\'http://www.moooyo.com\')+\'&rcontent=\',\'_blank\',\'scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes\'); void 0\" style=\"color:#000000;text-decoration:none;font-size:12px;font-weight:normal\"><SPAN style=\"PADDING-RIGHT: 5px; PADDING-LEFT: 5px; FONT-SIZE: 12px; PADDING-BOTTOM: 0px; MARGIN-LEFT: 10px; CURSOR: pointer; PADDING-TOP: 5px\"><IMG alt=分享到百度收藏 src=\"http:\/\/www.baidu.com\/favicon.ico\" align=absMiddle border=0 width=\"16\" height=\"16\" />&nbsp;分享到百度收藏<\/SPAN><\/a>");

document.writeln("<a href=\"javascript:window.open(\'http:\/\/www.kaixin001.com\/repaste\/share.php?rtitle=\'+encodeURIComponent(document.title.substring(0,76))+\'&rurl=\'+encodeURIComponent(\'米柚网，欢乐的单身交友平台，欢迎大家的加入。\')+\'&rcontent=\',\'_blank\',\'scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes\'); void 0\" style=\"color:#000000;text-decoration:none;font-size:12px;font-weight:normal\"><SPAN style=\"PADDING-RIGHT: 5px; PADDING-LEFT: 5px; FONT-SIZE: 12px; PADDING-BOTTOM: 0px; MARGIN-LEFT: 10px; CURSOR: pointer; PADDING-TOP: 5px\"><IMG alt=分享到开心网 src=\"http:\/\/img1.kaixin001.com.cn\/i\/favicon.ico\" align=absMiddle border=0 width=\"16\" height=\"16\" />&nbsp;分享到开心网<\/SPAN><\/a>");

document.writeln("<a href=\"javascript:window.open(\'http:\/\/v.t.sina.com.cn\/share\/share.php?title=\'+encodeURIComponent(\'米柚网，欢乐的单身交友平台，欢迎大家的加入。\')+\'&url=\'+encodeURIComponent(\'http://www.moooyo.com\')+\'&rcontent=\',\'_blank\',\'scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes\'); void 0\" style=\"color:#000000;text-decoration:none;font-size:12px;font-weight:normal\"><SPAN style=\"PADDING-RIGHT: 5px; PADDING-LEFT: 5px; FONT-SIZE: 12px; PADDING-BOTTOM: 0px; MARGIN-LEFT: 10px; CURSOR: pointer; PADDING-TOP: 5px\"><IMG alt=分享到新浪微博 src=\"http:\/\/t.sina.com.cn\/favicon.ico\" width=\"16\" height=\"16\" align=absMiddle border=0>&nbsp;分享到新浪微博<\/SPAN><\/a>");

document.writeln("<a href=\"javascript:window.open(\'http:\/\/share.v.t.qq.com\/index.php?c=share&a=index&f=q2&url=\'+encodeURIComponent(\'http://www.moooyo.com\')+\'&appkey=801165825&assname=&title=\'+encodeURIComponent(\'米柚网，欢乐的单身交友平台，欢迎大家的加入。\')+\'&pic=&rcontent=\',\'_blank\',\'scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes\'); void 0\" style=\"color:#000000;text-decoration:none;font-size:12px;font-weight:normal\"><SPAN style=\"PADDING-RIGHT: 5px; PADDING-LEFT: 5px; FONT-SIZE: 12px; PADDING-BOTTOM: 0px; MARGIN-LEFT: 10px; CURSOR: pointer; PADDING-TOP: 5px\"><IMG alt=分享到腾讯微博 src=\"http:\/\/mat1.gtimg.com\/app\/opent\/images\/websites\/share\/weiboicon16.png\" align=absMiddle border=0 width=\"16\" height=\"16\" />&nbsp;分享到腾讯微博<\/SPAN><\/a><\/div>");

